### ISSUE TITLE
Why delete v0 version?

### ISSUE THREAD

**Issue by azumads** [go-authboss/authboss#108]
It's really sucks for project online.

**Comment by aarondl** [comment]
My understanding of gopkg.in is that v0 is pre-release and that using that
version number simply gets you the latest default branch which is
undesirable. We've now got a v1.0.1 tag and I'd encourage you to use that.

I apologize for this disruption, but Go's package management is lackluster
(for now). I would advise you to vendor the project at v0 if you need that
specific version.

Also the move to v1 is part of a larger plan to release v2 which will bring
many improvements and so is a temporary pain for a long term gain.

Again I'm quite sorry, but do vendor projects in the future. It's the only
way in Go to be safe from breaking changes like this.

**Comment by azumads** [comment]
> v1 will be removed 6 months after the release of v2

That means at someday our project will can't build again,  it like a bomb that will explode in sudden.

Also if  we can get the packge in a normal `go get github.com/go-authboss/authboss`, that won't have this problem.

**Comment by aarondl** [comment]
This is only true if you're using github as a canonical source for your code. Meaning that you always build and fetch your code using `go get` which is considered a bad practice when you need to reliably build something. When you are building software you have to assume that repositories may vanish, change unexpectedly in breaking ways etc. That's the nature of dependencies, hence there's two options:

1. Accept that there will be breaking changes eventually, and keep your apps up to date when it breaks
2. Use vendoring https://golang.org/cmd/go/#hdr-Vendor_Directories to ensure that your code builds forever, no matter what they do upstream

This unfortunately has nothing to do with the way authboss is being managed, but how you are building and managing your own project. Once again I apologize for the breaking change - it's not something I do lightly and was necessary to move forward and allow people to use v1 for the interim (because of the gopkg.in works)
