### ISSUE TITLE
Is registerPostHandler() transaction safe?

### ISSUE THREAD

**Issue by Qs-F** [go-authboss/authboss#117]
[register.go](https://github.com/go-authboss/authboss/blob/v1.0.2/register/register.go)

I think registerPostHandler() is not transaction safe.

Is it too hard to manage database by only two interface, Get() and Put() ?

**Comment by aarondl** [comment]
When you say "transaction safe" you're referring to the fact that the `Get()` and the `Create()` don't happen inside a transaction so the user could race to be created?

It's possible due to the lack of transactions here that (threads 1 and 2):
2 - User is checked for existence: is not there yet
1 - User is checked for existence: is not there yet
2 - User is created here
1 - Handler tries to create but user exists and fails with an error

I'm trying to imagine other scenarios that could happen but I think this is all of them. `Create` itself could use a transaction if you wanted it to in your storer implementation.

And the reason we have the `Create()` instead of only `Put()` is we need to define the difference between "save existing" and "create new", because it's important for registration. We could attempt to use transactions to ensure that the user doesn't exist beforehand before creation instead, but that would complicate the interface much more than a `Create()` method does.

Now is the time to think about this though while I'm developing v2. Looking forward to your comments.

**Comment by Qs-F** [comment]
Oh, I'm sorry but I haven't rearized your reply…

> don't happen inside a transaction so the user could race to be created?

Exactly, I rethought this after I commented. You are right:)  
I'm sorry for that. And maybe I could use authboss correctly now. Thank you very much.

> And the reason we have the Create() instead of only Put() is we need to define the difference between "save existing" and "create new", because it's important for registration. We could attempt to use transactions to ensure that the user doesn't exist beforehand before creation instead, but that would complicate the interface much more than a Create() method does.

I have one more question about this. In my system, `Put` and `Update` is separated. This means if the specificed key is existed, system can't put data on kvs. So if I want to use authboss, should I make `Put` updatable?

**Comment by aarondl** [comment]
Yep, put should be an update operation. Sorry I missed your reply to this too. Closing since there should be no issue here.
