### ISSUE TITLE
User is logged in after confirming his account

### ISSUE THREAD

**Issue by kaiomagalhaes** [go-authboss/authboss#123]
Hey @aarondl isn't it a security flaw? let's look at the following user case:

1. User registers on an application
2. User receives a confirmation email
3. Someone accesses the user email
4. Someone sees that the user has an account on that application and clicks on confirm
5. This person now can do whatever he wants 

Is there any reason to make it this way? I just saw that on the confirmation process a session is created

```
ctx.SessionStorer.Put(authboss.SessionKey, key)
```

Should it really be happening?

**Comment by kaiomagalhaes** [comment]
@aarondl seems that the same happens for the password update after recovery, isn't it another security flaw?

**Comment by aarondl** [comment]
Hm. Definitely a fair statement. I'm happy to evaluate other workflows. Currently it's done out of convenience (which is usually at odds with security). Anecdotally most sites don't force a log-in after an e-mail is confirmed, though most public sites also allow usage of the site before e-mail confirmation too.
A potential fix is to allow Authboss developers to choose if a user can log in without confirming their e-mail first, and then never create sessions for users who click the confirm/recover e-mail. What are your thoughts?

I'd look to devise to see what they do too, since that library is old and wise at this point in time, the options for confirmable say a few things:
```text
* +allow_unconfirmed_access_for+: the time you want to allow the user to access their account
  before confirming it. After this period, the user access is denied. You can
  use this to let your user access some features of your application without
  confirming the account, but blocking it after a certain period (ie 7 days).
  By default allow_unconfirmed_access_for is zero, it means users always have to confirm to sign in.
* +reconfirmable+: requires any email changes to be confirmed (exactly the same way as
  initial account confirmation) to be applied. Requires additional unconfirmed_email
  db field to be set up (t.reconfirmable in migrations). Until confirmed, new email is
  stored in unconfirmed email column, and copied to email column on successful
  confirmation.
* +confirm_within+: the time before a sent confirmation token becomes invalid.
  You can use this to force the user to confirm within a set period of time.
  Confirmable will not generate a new token if a repeat confirmation is requested
  during this time frame, unless the user's email changed too.
```

Same is true of the recoverable:
```text
* +reset_password_keys+: the keys you want to use when recovering the password for an account
* +reset_password_within+: the time period within which the password must be reset or the token expires.
* +sign_in_after_reset_password+: whether or not to sign in the user automatically after a password reset.
```

Authboss is missing a majority of these options and only has one prescriptive workflow that has this vulnerability (or convenience depending on how you look at it :p)

**Comment by aarondl** [comment]
The highlighted answer here is also really good information about how it works: http://stackoverflow.com/questions/18655334/avoid-sign-in-after-confirmation-link-click-using-devise-gem

**Comment by codelitt** [comment]
IMHO, if the library doesn't log you in (creating a session) when you sign up and there is authenticated session attached to the users browser, then it definitely shouldn't log you in automatically (create a session) when you click on the link. The user hasn't been required to enter the password used when signing up yet is able to to have full access to the account. 

I think regardless of whether the lib signs you in and creates a session as you finish sign up, it should check for a previously authenticated session or require the password before giving you access to the users account. 

Password recovery is harder. You're essentially allowing whoever has access to this email to reset the password so they've just entered the new password. Automatically giving them a session or not is negligible. You can't really solve this security issue without implementing 2FA. For sure though, the password recovery process should invalidate all existing sessions and send a notification that the password has been changed.

**Comment by kaiomagalhaes** [comment]
So for now we could include a "LOG_IN_AFTER_CONFIRM" option on the struct that would be checked. What do you think? I could do it and send a PR.

**Comment by aarondl** [comment]
I'd rather follow the way they're doing this in Devise. `AllowInsecureLoginAfterConfirm` adding the word Insecure in there makes people think twice about enabling it. The functionality can stay as we're discussing, but the name has to be something scary looking. I'd be happy to accept a PR that introduced this functionality. Since it's in the same vein, is it possible to add the `SignInAfterResetPassword` flag as well? It's essentially the same change, just in a different module.

Longer term after the 2.0 rewrite's all said and done I'd like to implement the rest of the pieces above. I will try and hurry on this point, the more code we write against the old, the harder it'll be :(

**Comment by kaiomagalhaes** [comment]
Agreed @aarondl it makes sense. I will work on it through the weekend, will implement both.

**Comment by kaiomagalhaes** [comment]
@aarondl @codelitt I've created the following PR's. I believe that after merging them we can close this issue: #125 #126

**Comment by kaiomagalhaes** [comment]
As everything is merged I'm closing this issue
