### ISSUE TITLE
Use simple redirects instead of templates?

### ISSUE THREAD

**Issue by iKonrad** [go-authboss/authboss#124]
Hi
Thanks for this great library. 
I'm making my first steps in Go/Authboss and I'm trying to wrap my head around how to encapsulate authboss with my React.js application.

So essentially, React handles all the routing and displays the appropriate page based on the URL. All Golang is doing, is just rendering the React object on the server and sends it to the client.

With that said, how I can replace templates in authboss with simple redirects or JSON responses? 
So when the user creates an account, it's either redirecting to /register/complete (and let React do its job), or make it working entirely through the API (ajax -> /auth -> return JSON)?

Thanks

**Comment by aarondl** [comment]
Hey there @iKonrad, in the dev branch I'm working on a 2.0 rewrite that does exactly what you're asking for. It makes it easy to do JSON responses instead of HTML/Redirects and will typically when it wants to do a redirect provide you with a JSON object that shows what the redirect would have been, what the flash message would have been, and what the path to redirect is, so that you can perform the action in Javascript.

It's not that far off from ready (authboss package is mostly done, only modules left and then cleanup) but my time's been pretty limited to work on this recently. I'm going to close this issue because I consider it a main goal to support what you're asking for in this rewrite. Thanks for your interest in authboss :)
