### ISSUE TITLE
Bearer Tokens? JWT? Claims Based?

### ISSUE THREAD

**Issue by aarondl** [go-authboss/authboss#53]

**Comment by aarondl** [comment]
The more I think and research about this, the more I think a custom SessionStorer that does JWT tokens is all that needs doing here. Direct support from Authboss seems of little utility since we've already abstracted this part out. If there are any issues with an implementation that requires authboss I'm ready to lend a hand to anyone attempting to implement.

**Comment by oliverdain** [comment]
@aarondl can you provide some hints on how this might work. There doesn't appear to be anything called `SessionStorer`. There is `ServerStorer` but it never gets access to the request. I thought maybe I could do in a `ClientStateReadWriter` but while that gets access to the request I don't think there's any way to attach anything to the requests context because you get a `*http.Request` and not a `**http.Request`.

I can read the JWT token out of a header in my `ClientStateReadWriter` but I can't figure out how to propagate to the rest of the code (e.g. so I can read it out of the context in an endpoint).
