### ISSUE TITLE
Use array of strings

### ISSUE THREAD

**Issue by 0xdabbad00** [go-authboss/authboss#60]
Please use an array of strings here: https://github.com/go-authboss/authboss/blob/master/callbacks.go#L26

Example:
```go
var eventNames = [...]string{"EventRegister", "EventAuth", "EventOAuth", "EventAuthFail", "EventOAuthFail", "EventRecoverStart", "EventRecoverEnd", "EventGet", "EventGetUserSession", "EventPasswordReset"}
```

It won't be `const` anymore, but it's a lot cleaner.  As an example, Go's own source does this here: https://github.com/golang/go/blob/master/src/time/time.go#L94

**Comment by aarondl** [comment]
The code that you're referring to is generated by a tool created by the Go team designed to create String() methods for "enumerations" in Go.

https://godoc.org/golang.org/x/tools/cmd/stringer

The code that's generated is more efficient and because it's generated it shouldn't be maintained by people and therefore shouldn't need to be evaluated for cleanliness, you simply edit the enumeration adding or removing whatever you like and call ```go generate``` again.

I have done something bad in this case though, in order to eliminate the extra file as well as the ugly names generated by the tool we copied and changed the code that the tool generated, which I admit defeats the purpose. It will be corrected to use the tool correctly. Thanks for your feedback :)

**Comment by aarondl** [comment]
@0xdabbad00 I hope this is satisfactory.
