### ISSUE TITLE
How not to use a global DB?

### ISSUE THREAD

**Issue by NCSantos** [go-authboss/authboss#66]
Hi,

On the authboss-sample how do I create a not global DB connection to use on the storer, OAuth2Storer, and on my handlers?

Thanks for your help.

**Comment by aarondl** [comment]
Depends what you mean by "not global DB connection."

What's the purpose behind not using a global db connection? Also you could simply make a Storer implementation that opens the database each time it wants to do any operations.

**Comment by NCSantos** [comment]
Hi

Thanks for your reply.

I'm new to go, and from what I've been reading globals lead to bad coding practices.

**Comment by aarondl** [comment]
Globals have often been touted as a "bad practice". But in the land of Go, a global database connection is not a terrible thing because it's never one connection. It's actually a connection pool and is safe for use by multiple goroutines at the same time. This means that you will only ever have one instance of your database "connection" anyways.

The only bad thing about having this is testing. But I'll leave it as an exercise for the reader to determine how to test around global variables.

If you would like to not have a global database variable, you could store the connection in your storer implementation. The way we have it in Authboss is correct, it's assigned once and long lived (but also not global). The sample is just showing you one way to program a sample application, you don't have to follow it verbatim :)
