### ISSUE TITLE
Auth: validateCredentials configurable

### ISSUE THREAD

**Issue by guilherme-santos** [go-authboss/authboss#67]
Hi,

My password are encrypted in different way (we do not use bcrypt), what do you think, to create config to use a different function to compare.

What I'm imaging it's update after [this line](https://github.com/go-authboss/authboss/blob/master/auth/auth.go#L144), we can verifiy if has a configuration, if not use default one, and call ```func VerifyPassword(user authboss.Attributes, password string) (bool, error)```
and the user implement how he wants.

What do you think, I can try implement that!

**Comment by aarondl** [comment]
Hi Guilherme,

I think the architecture of authboss benefits slightly from a single password column in the database. Other schemes (except scrypt, which I don't think is a good idea given it's newness) would need a second column to store a password salt, or be very insecure.

What scheme do you use and why? I was under the impression that the only option was scrypt or bcrypt, and so I'm curious what else there is out there, and whether or not we should be supporting it in Authboss.

**Comment by guilherme-santos** [comment]
Hi,
Actually, I'm working with legacy database where they are using sha256 with a salt.. It's not an option to me migrate all the database to encrypt using bcrypt because it's another system that add new users and permit to log in.

**Comment by aarondl** [comment]
Aha. Sorry to say but I won't support weak forms of cryptography in Authboss. SHA256 (assuming one round of hashing) + salt is easily crackable when compared to slow hashes like bcrypt or scrypt. I feel like it's an anti-goal to allow Authboss to support these schemes and would rather than encourage users to migrate away from insecure software or cryptography schemes. So I'll recommend that you make these changes in a fork.

It's also bigger than you'd want because not only do you have to replace the uses of bcrypt (there are not many) but adding a salt database column alongside the password is required. If you require any support to make this change we can chat here https://gitter.im/go-authboss/authboss

Thanks for your interest in Authboss, and sorry I keep saying no haha.

**Comment by guilherme-santos** [comment]
I understand and agree what you say, but sounds perfect when you are creating new software, but this make impossible use this project with legacy one, as I told you other internal apps add new users and other one make login, my new app it's only one more that is doing that.

But it's ok, probably I'll do it in a fork
