### ISSUE TITLE
Add default to other types on Bind

### ISSUE THREAD

**Issue by guilherme-santos** [go-authboss/authboss#69]
I have a field of [bson.ObjectId](http://godoc.org/gopkg.in/mgo.v2/bson#ObjectId) but Bind function don't work with that, what do you thing to add a default to [this line](https://github.com/go-authboss/authboss/blob/master/storer.go#L262)?

**Comment by kris-runzer** [comment]
Which Authboss field are you trying to bind to an ObjectID?  Perhaps attach a code snippet of what you are trying to achieve.

**Comment by guilherme-santos** [comment]
I have some fields that is important to my application, uuid (generate in mongo, for that I need ObjectId), I have other field that is an array, and currenct code don't handle that..

**Comment by aarondl** [comment]
@guilherme-santos I think Kris is asking to see your user struct, the one you're trying to store with the ObjectId in it.

Keep in mind that authboss supports the [sql.Scanner](http://golang.org/pkg/database/sql/#Scanner) and [driver.Valuer](http://golang.org/pkg/database/sql/driver/#Valuer) types. So it can serialize any type that can serialize into the database by adding these functions to an aliased type. We chose to support this over our own custom implementation because people already use a lot of types that use this.

Also authboss will never be able to DIRECTLY support mgo.ObjectId because then we would have to reference mgo, which would bring in the package, which would create a dependency on mgo for authboss, making every authboss user have the mgo package, which is something we can't have obviously.

**Comment by guilherme-santos** [comment]
I understand you.. How I've said I don't want you add mgo dependecy, but add a default statement when you try Bind/Ubind user struct... In [this switch](https://github.com/go-authboss/authboss/blob/master/storer.go#L262) you can add:
```
default:
    field.Set(reflect.ValueOf(val))
```
And [this switch](https://github.com/go-authboss/authboss/blob/master/storer.go#L330) you can add:
```
default:
    attr[name] = field.Interface()
```

Add that, bson.ObjectId that maps to string, will be fixed, and you can have arrays or slices in your struct, that will make works too.

What do you think?

**Comment by aarondl** [comment]
This requires more consideration. Will ponder it this weekend. Allow me that time to consider the ramifications of this change and see if it's viable.
