### ISSUE TITLE
User is fetched from a storer twice

### ISSUE THREAD

**Issue by orian** [go-authboss/authboss#79]
The method [`(ab *Authboss) currentUser`](https://github.com/go-authboss/authboss/blob/master/authboss.go#L96) requests a user data from storer twice.

First time in ctx.LoadUser and the second time later on. Why is it like that?

**Comment by aarondl** [comment]
We actually used to cache it. But there's problems with that in that what happens if during the request an update to the user is made? Then you're operating on stale data. Then we have to consider versioning etc. So this trade-off was made. Nothing stops you from caching the current user with your own request contexts.

**Comment by orian** [comment]
I cache it after I get it into my app. I was just monitoring SQL and noticed unexpected number of queries  by a number of x2.

What do you mind by 'your own request contexts'?

**Comment by kris-runzer** [comment]
In your storer you can put your caching logic that you desire when you implement the Get(key string) (interface{}, error) method.

**Comment by aarondl** [comment]
1. This part of the response assumes you're talking about during a request, you see multiple database accesses because different handlers are calling currentUser:

Authboss requests themselves should be fairly far and few between (I mean requests that actually go through the Authboss router, that means anything dealing with login/logout/recover/remember etc). Only at this time will the user be inefficiently fetched.

For your own handlers (your own portion of the web app) say for example you're working on a store. The shopping cart, the product pages can all fetch the user and store it in "your own contexts" (gorilla context, the go "standard" context) to avoid accessing it twice.

2. If you're saying that lines:
https://github.com/go-authboss/authboss/blob/master/authboss.go#L96
https://github.com/go-authboss/authboss/blob/master/authboss.go#L100
Actually query the database twice somehow than that makes no sense and is a bug. I don't believe that this is the case as you can see clearly that it directly returns either or so it can't call both unless currentUser is being called multiple times by something.

To figure out which case this is, simply drop some stack trace emitting into `currentUser()` and see whose calling it during your requests. If it's an authboss problem I will correct it quickly for you as that's a bad bug :)

**Comment by orian** [comment]
Let me be clear. I'm talking about lines:
https://github.com/go-authboss/authboss/blob/master/authboss.go#L86
https://github.com/go-authboss/authboss/blob/master/authboss.go#L96

I assume something may happen between them (some callback). Just saying the user is fetched almost one after the other without any saves.

**Comment by aarondl** [comment]
Sorry I've been really busy. I see what you're talking about (dunno how I missed it to be honest). I'll get it fixed this weekend :)

**Comment by orian** [comment]
That's fine. Just want you to be aware of it. Thanks for reply :)
