### ISSUE TITLE
Security audit

### ISSUE THREAD

**Issue by buu700** [go-authboss/authboss#82]
Any interest in having Authboss audited? It would make me *a lot* more confident in choosing it over some of the other options, and it seems like it'd be a perfect fit for OTF funding: https://www.opentech.fund/lab/red-team-lab

**Comment by aarondl** [comment]
Well, you may have noticed that this project is not undergoing any improvements lately. I actively maintain it in that PR's and Pull Requests are typically dealt with in a timely fashion (except 2). But we haven't really released a v1 on gopkg.in or a tag.

The core reason for this has nothing to do with security or badness of any kind. But we feel like we've designed this for the wrong language. We set out to create Devise for Go. I think we largely succeeded but it was the wrong goal. We should have been shooting for something to easily secure APIs since that's what most people use Go for.

I've currently got no interest in rewriting Authboss for APIs because I don't have a use case for it currently. But eventually I will probably do it, and at that point I'd welcome going down the path of security audits etc.

I'm not going to dissuade someone from going through the effort. I'll support them and help rectify any security bugs found as well. Hit me up on gitter if you're interested in pursuing this.
