### ISSUE TITLE
How to get Request in function map?

### ISSUE THREAD

**Issue by binku87** [go-authboss/authboss#84]
```
var funcs = template.FuncMap{
	"formatDate": func(date time.Time) string {
		return date.Format("2006/01/02 03:04pm")
	},
	"yield": func() string { return "" },
}

ab.Layout = template.Must(template.New("layout").Funcs(funcs).Parse(string(b)))
```

Like this one, How i can get request in function map?

I would like to do things like this:
```
var funcs = template.FuncMap{
	"aHelperNeedRequest": func(r *http.Request) string {
		return ""
	},
}
```

**Comment by aarondl** [comment]
This isn't actually a supported use case right now in Authboss. We have very little data available to the views and it was somewhat intentional. We're open for pull requests but have no intention of adding this feature at this time.

An example of where the data for a view is being defined:
https://github.com/go-authboss/authboss/blob/586415a7db9d2b1538cd2c05ca2dbbce0ee9cc62/register/register.go#L128

An example of the data being consumed in the template:
https://github.com/go-authboss/authboss/blob/586415a7db9d2b1538cd2c05ca2dbbce0ee9cc62/internal/response/templates/register.html.tpl

Your templates will have access to the same data, but nothing more. Again though, I'm happy to consider code that would make this feature possible in a generic way.

**Comment by binku87** [comment]
I see. The case i face is like this:

1. We have function `t` in layout template anywhere. the `t` used to translation, e.g. `{{ t "header.title" }}`
2. And the `t` function need context (Request) to known which language's translation need to be display.

I think this case it is normal, right?

**Comment by aarondl** [comment]
I agree. Context and i8n is something we'd be looking at for authboss 2.
Which as more of these kinds of requests come in, we're considering
spending time on more and more. As I said though I'd be happy to accept
code that makes this possible!
